### ISSUE TITLE
info

### ISSUE THREAD

**Issue by atarbig** [cromize/beatport_tracktagger#1]
how this work?

**Comment by cromize** [comment]
Hello, what you see here is my toy implementation of a tagger for music files. It's able to assign general tags, from beatport using beatport ID. My motivation was absence of ID3 tags in bought wav beatport files. It's not currently ready, because it lacks documentation and other stuff, but the core idea works. You can invoke it with parameter -h to see help. Need to parallelize it though, for large amounts of tracks.

**Comment by cromize** [comment]
Added info into README.
